image:
  file: .gitpod/Dockerfile

additionalRepositories:
  - url: https://github.com/gitpod-io/gitpod
    checkoutLocation: gitpod

tasks:
  - init: |
      go install ./...
    command: |
      # Install commitlint
      npm i -g @commitlint/{config-conventional,cli}

      # Install husky
      npm i -g husky

      # Activate hooks
      husky install

      # Remove anything already on dev cluster
      kubectl delete -f ./config/samples || true
      make uninstall || true

      # Install to dev cluster
      make install
      kubectl apply -f ./config/samples

      # Run run run!!!
      make run
    env:
      ENABLE_WEBHOOKS: false

ports:
  - port: 8080
    name: operator
    onOpen: notify
  - port: 8081
    name: health
    onOpen: notify


vscode:
  extensions:
    - donjayamanne.git-extension-pack
    - EditorConfig.EditorConfig
    - golang.go
