image:
  file: .gitpod/Dockerfile

tasks:
  - init: |
      go install ./...
      make run
    command: |
      # Install commitlint
      npm i -g @commitlint/{config-conventional,cli}

      # Install husky
      npm i -g husky

      # Activate hooks
      husky install
    env:
      ENABLE_WEBHOOKS: false
  - init: |
      kubectl apply -f ./config/samples

ports:
  - port: 8080
    name: operator
    onOpen: notify
  - port: 8081
    name: health
    onOpen: notify


vscode:
  extensions:
    - donjayamanne.git-extension-pack
    - EditorConfig.EditorConfig
    - golang.go
